dist: bionic
language: minimal
notifications:
  email: false
script: 
  - docker build -t dongzhuoer/ci:$tag -f $tag.Dockerfile .
  - bash +x deploy.sh

jobs:  
  include:
    - stage: build
      env: tag=base
    - stage: test
      env: tag=base
      script: bash +x test-$tag.sh
