dist: bionic
language: minimal
notifications:
  email: false

jobs:  
  include:
    - stage: build
      name: base
      script: bash +x script.sh base  
    - stage: test
      name: base
      script: skip
