dist: bionic
language: minimal
notifications:
  email: false
script: 
  - docker build -t dongzhuoer/ci:$tag -f $tag.Dockerfile .
  - bash +x deploy.sh

jobs:  
  include:
    - stage: build
      name: place holder  
      script: skip  # without this toy job, comment first book would cuase error      
    - name: base
      env: tag=base
    - stage: test
      name: place holder  
      script: skip  # without this toy job, comment first book would cuase error      
    - name: base
      script: bash +x test-base.sh
